import uuid
import csv

mac_addresses = []
d_ids = []
p_ids = []

with open('generated_doctors_data.csv', 'r', encoding="utf8") as csv_read_file:

    # reader object
    csv_reader = csv.DictReader(csv_read_file)

    for line in csv_reader:
        d_ids.append(line['d_id'])
        mac_addresses.append(line['Assigned_PC'])


with open('/home/dipamvasani7/Desktop/generated_patient_data.csv', 'r', encoding='utf8') as csv_read_file:

    csv_reader = csv.DictReader(csv_read_file)

    for line in csv_reader:
        p_ids.append(line['p_id'])

# test if d_ids are unique
print(len(d_ids))
d = set(d_ids)
print(len(d))

# test if mac addresses are unique
print(len(mac_addresses))
m = set(mac_addresses)
print(len(m))

# append a list to another list
# this is done in order to check if the d_ids and p_ids are same
# because they have been generated by the same method
d_ids.extend(p_ids)

print(len(d_ids))
d = set(d_ids)
print(len(d))
