import uuid
import csv

# in this file we will store 2 dictionaries
# the first dictionary will contain d_ids as the key
# and the assigned pcs as the value
# the second dictionary will contain p_ids as the key
# and the assigned d_ids as the value
# this will then be imported in the accesses code
# to be used throughout data generation

doctors_pc = {}
patients_doctor = {}
doctors_grants = {}

mac_addresses = []
d_ids = []
p_ids = []

with open('generated_doctors_data.csv', 'r', encoding="utf8") as csv_read_file:

    # reader object
    csv_reader = csv.DictReader(csv_read_file)

    for line in csv_reader:
        d_ids.append(line['d_id'])
        mac_addresses.append(line['Assigned_PC'])

        doctors_pc[line['d_id']] = line['Assigned_PC']
        doctors_grants[line['d_id']] = [line['Accesses'], line['Grants']]
        # print(doctors_grants)
        # print(doctors_pc)


with open('generated_patient_data.csv', 'r', encoding='utf8') as csv_read_file:

    csv_reader = csv.DictReader(csv_read_file)

    for line in csv_reader:
        p_ids.append(line['p_id'])

        patients_doctor[line['p_id']] = line['d_id']
        # print(patients_doctor)

# test if d_ids are unique
print(len(d_ids))
d = set(d_ids)
print(len(d))

# test if mac addresses are unique
print(len(mac_addresses))
m = set(mac_addresses)
print(len(m))

# append a list to another list
# this is done in order to check if the d_ids and p_ids are same
# because they have been generated by the same method
d_ids.extend(p_ids)

print(len(d_ids))
d = set(d_ids)
print(len(d))
